# Generated by Django 4.1.3 on 2022-12-03 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='modeloDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horarioi', models.TimeField()),
                ('horariof', models.TimeField()),
                ('status', models.FloatField()),
                ('decorrido', models.IntegerField()),
                ('dispositivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dispositivos.modelodispositivo')),
            ],
        ),
    ]
