# Generated by Django 4.1.3 on 2022-12-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='modeloDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, null=True)),
                ('objetivo', models.CharField(max_length=150, null=True)),
                ('urlcloud', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
